"""status columm change to int

Revision ID: 744c475d3542
Revises: 8bb9b5b592b7
Create Date: 2026-04-11 20:29:11.580868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "744c475d3542"
down_revision: Union[str, Sequence[str], None] = "8bb9b5b592b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Для таблицы plan_requests
    op.execute(
        """
        ALTER TABLE plan_requests 
        ALTER COLUMN status TYPE INTEGER 
        USING (
            CASE status::text
                WHEN 'DRAFT' THEN 0
                WHEN 'IN_PROGRESS' THEN 10
                WHEN 'COMPLETED' THEN 20
                ELSE 0 
            END
        )
    """
    )

    # 2. Для таблицы plans
    op.execute(
        """
        ALTER TABLE plans 
        ALTER COLUMN status TYPE INTEGER 
        USING (
            CASE status::text
                WHEN 'DRAFT' THEN 10
                WHEN 'IN_PROGRESS' THEN 50
                WHEN 'COMPLETED' THEN 100
                ELSE 10 
            END
        )
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plans",
        "status",
        existing_type=sa.Integer(),
        type_=postgresql.ENUM("DRAFT", "IN_PROGRESS", "COMPLETED", name="status"),
        existing_nullable=False,
    )
    op.alter_column(
        "plan_requests",
        "status",
        existing_type=sa.Integer(),
        type_=postgresql.ENUM("DRAFT", "IN_PROGRESS", "COMPLETED", name="status"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
